run:
  timeout: 5m
  tests: false
output:
  format: github-actions
linters:
  enable:
    - revive # replacement for golint
    - dupl # check duplicated code
    - goconst # check strings that can turn into constants
    - gofmt # check fmt
    - goimports # check imports
    - gocyclo # check complexity
linters-settings:
  gocyclo:
    min-complexity: 30
